baseURL = "https://Offliners.github.io"
title = "Offliner's Blog"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
disqusShortname = "offliners"
googleAnalytics = "G-WFQ2VM3C00"

[params]
    author = "Offliner"
    badge = "orange"
    quote = "red"
    notice = "Hello! Welcome to Offliner's Blog."
    notice_color = "red"
    index_posts_num = 5
    google_search = true
    math = true
    logo = "images/Offliner.png"
    portrait = "images/Offliner.png"
    bio = """
    <p> Hi there, l'm Offliner. </p>
    <br />
    <p>Try anything I want to try!</p>
    """

[[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/gallery/"
    weight = 1

[[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "Offliner"
    url = "/about/"
    weight = 2

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[[menu.icon]]
    url = "mailto:eric21904@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Offliners/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/Offliner8"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/offliner21904/"
    name = "instagram"
    weight = 1
